name: arcgis_map_sdk_ios
description: Esri ArcGIS Flutter iOS implementation.
version: 0.8.0
repository: https://github.com/fluttercommunity/arcgis_map_sdk
maintainer: Stefan Schaller (@stefanschaller), Julian Bissekkou (@JulianBissekkou)

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  arcgis_map_sdk_method_channel: ^0.8.0
  arcgis_map_sdk_platform_interface: ^1.0.1

  flutter:
    sdk: flutter

dev_dependencies:
  lint: ^2.0.0

flutter:
  plugin:
    implements: arcgis_map_sdk
    platforms:
      ios:
        pluginClass: ArcgisMapPlugin
        dartPluginClass: IosArcgisMapPlugin
