name: arcgis_map_sdk
description: Esri ArcGIS map for Flutter for Web, iOS and Android platforms
version: 0.8.0
repository: https://github.com/fluttercommunity/arcgis_map_sdk
maintainer: Matthaios Saitakis (@MatthaiosSait), Stefan Schaller (@stefanschaller), Julian Bissekkou (@JulianBissekkou), 
  Pascal Welsch (@passsy), Max Peters (@maxpeters)

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  arcgis_map_sdk_android: ^0.8.0
  arcgis_map_sdk_ios: ^0.8.0
  arcgis_map_sdk_platform_interface: ^1.0.1
  # todo: this was removed to make sure we don't end up with web artifacts in our mobile build
  # this is only a temporary solution.
  #arcgis_map_sdk_web: ^0.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  lint: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: arcgis_map_sdk_android
      ios:
        default_package: arcgis_map_sdk_ios
      web:
        default_package: arcgis_map_sdk_web

topics:
  - map
  - arcgis
