name: arcgis_map_sdk_android
description: Esri ArcGIS Flutter Android implementation.
version: 0.8.0
repository: https://github.com/fluttercommunity/arcgis_map_sdk
maintainer: Stefan Schaller (@stefanschaller), Julian Bissekkou (@JulianBissekkou)

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  arcgis_map_sdk_method_channel: ^0.8.0
  arcgis_map_sdk_platform_interface: ^1.0.1

  flutter:
    sdk: flutter

dev_dependencies:
  lint: ^2.0.0

flutter:
  plugin:
    implements: arcgis_map_sdk
    platforms:
      android:
        package: dev.fluttercommunity.arcgis_map_sdk_android
        pluginClass: ArcgisMapPlugin
        dartPluginClass: AndroidArcgisMapPlugin
